version: '3.1'
services:
  bd-users:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bd-users
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
